### ISSUE TITLE
Personal Laser MK2

### ISSUE THREAD

**Issue by DanielNagy** [jimmyjon711/FactorioExtended-Equipment#11]
Please re-balance the  "Personal Laser Defense MK2" to use the "Personal Defense Laser MK1" in the recipe instead of "Laser Turret MK2"

It appears very un-extended like :D 

Thanks

**Comment by billbo99** [comment]
Fixed in #12 
https://github.com/jimmyjon711/FactorioExtended-Plus-Equipment/pull/12

**Comment by DanielNagy** [comment]
Having the MK2 Laser Turret remaining might be too expensive. Although Trying to determine what kinda formula's are used for extended plus items show no consistency with items. So its kinda hard to suggest what it should look like..

**Comment by billbo99** [comment]
With most FE+ recipies the cost is bump in the ingredients from the previous recipie along with 2x items of the previous tier.  EG   
Repair Pack mk1 (2x Iron Gear + 1x Electronic Circuit)
Repair Pack mk2 (1x Iron Gear + 1x Advanced Circuit + 2x Repair Packs mk1)
Repair Pack mk3 (1x Iron Gear + 1x Processing Unit + 2x Repair Packs mk2)


Since there was no way to get a next tier of Processing Units or LDS,  I added the Personal Battery mk2
PLD mk1 = (20x Processing Units + 5x LDS + 5x Laser turrets)
PLD mk2 = (5x Processing Units + 5x LDS + 5x Laser turrets mk2 + 2x PLD mk1 + 1x Personal Battery mk2)

Maybe the Laser turrets mk2 cost could be reduced to 2

**Comment by DanielNagy** [comment]
yeah, that makes sense I guess
